### ISSUE TITLE
Add safety training info

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#1]
@DeirdreLoughnan Can you add info (use a wiki page or create new folder or such!) on lab safety (e..g, what undergrad students must fill out, critical info etc.). _Zero rush on this._

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I drafted a wiki page for lab and field safety. If there is anything you think I am missing, let me know.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Thank you! Can you check for anything we need to update and then close this.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I can't think of any new information to add.
