### ISSUE TITLE
Add info on TAships

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#2]
@DarwinSodhi  As long as it's not info that should not be public, can you add info (folder with txt files or just build a wiki page) on getting TAships at UBC? _Zero rush on this._

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Did this ever get done? If not can you add some very simple info to a wiki page and close this?

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I don't think it was. 

I created a wiki page with the important links and general information:

https://github.com/temporalecologylab/labgit/wiki/Teaching-Assistantships-at-UBC
