### ISSUE TITLE
website: tumblr

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#20]
@DeirdreLoughnan wrote to @ngoj1 :

> Lizzie mentioned that you are managing the lab website and could help solve a mystery.
> 
> Apparently we received an email on June 17th that our Tumblr Feed was reaching the maximum 200 monthly views and would be deactivated.
> 
> Would you be able to log into the lab's temporalecologylab email and let Lizzie know if we have received emails like this before? 
> 
> If we are getting these a lot, could you look into how this might impact the website functionality?

**Comment by ngoj1** [comment]
We seem to be getting an email around once/twice a month about this warning (70% and 90% view limit) and this year so far, the widgets have been deactivated twice (16 March and 7 Feb) after which they reset on the 21st of the month. 
Here's a photo of the emails from Tumblr about this:
![image](https://github.com/temporalecologylab/labgit/assets/87724921/d4025a2f-4771-4b4c-9950-d043dd84a2d2)

It seems like only the widgets are negatively impacted by this, and if they don't do something that is essential to the lab then it should probably be fine to leave it as is. It might be worthwhile to upgrade to a higher plan if the Tumblr gets used for really important things that require high visitor traffic (maybe like if there were monthly talks/consortia/symposia/etc.?).

**Comment by lizzieinvancouver** [comment]
@ngoj1 Thanks for working on this! Do you know what happens when the widget is deactivated? People just can't see the photos on the main webpage or what?

**Comment by ngoj1** [comment]
> People just can't see the photos on the main webpage or what?

Yes exactly, when the widget gets deactivated we just don't get an "updates from our Tumblr" on the bottom of the homepage on temporalecology.org. I'm not sure what it would look like, I imagine it might just be a blank space there.

**Comment by lizzieinvancouver** [comment]
@ngoj1 Thanks for checking this. I feel like it is not a big deal (bigger deal - better website photos!) so am closing this.
