### ISSUE TITLE
AudioMoth Cases

### ISSUE THREAD

**Issue by kengi-neer** [temporalecologylab/labgit#22]
Initial Notes:

> [Application Notes](https://github.com/OpenAcousticDevices/Application-Notes/tree/master)
> - Injection-moulded; robust polycarbonate
> - Rain shield for acoustic vent
> - Original vents are Porelle AV5ID but GAW334 indicated in website (updated in the application notes early August)
> - Sufficient time needed after closing the case for pressure equalization (removed in latest update)
> 
> [“... in general any good quality acoustic membranes can be used”](https://www.openacousticdevices.info/support/device-support/how-to-fix-case-microphone-cover)

Right now, we are trying to make 30 3D-printed cases of a [model](https://www.thingiverse.com/thing:4763983) Jonathan's former student, Ross, found and its [modified version](https://www.thingiverse.com/thing:6153557).

Materials (with links for possible sources):
- O-ring (30 pcs) - 48mm OD, 44mm ID, 2mm Width, 70A hardness, nitrile rubber (Buna-N) - two of [these](https://www.amazon.ca/PATIKIL-Nitrile-Sealing-Plumbing-Automotive/dp/B0C14YWPB9/ref=sr_1_7?crid=3FZ7MXAPZFZPI&dib=eyJ2IjoiMSJ9.QR3NvMy-pzvx-hKxuJyPdjTTlN0vJSC1qlyt2l31ixpB36DqQ92VCUnkMnxUuoZnPiigw_MPmFipevOu_btnnn-k4L-q5wliRMzyEBRdNkrbYwgZa2yIskLJKUlD7q9dMEeS78MAfTRcs9RFo-BlnazSzMSxWBjXh1EP8BVgWuEbo1_gKf8y_p8WeL1-Uoxf40nh00ztxFYqfKWHYfQwGlAWWPwd8IZRbKf4EUaUMFEqnqLEW8fDHgzw-YBw3S_TlMaFkppSYEqtou1QCDwQBj9ZUJnvyEvqV9-7RLrARAU.A5vU7xHxrrxxH2AcrJmssKZ2kFHOe3nq_s_44TmQhNQ&dib_tag=se&keywords=o-ring%2B44mm%2BID%2C%2B48mm%2BOD%2C%2B2mm%2Bwidth&qid=1724254617&sprefix=o-ring44mm%2Bid%2C%2B48mm%2Bod%2C%2B2mm%2Bwidth%2Caps%2C115&sr=8-7&th=1)
- Hex Bolts and Nuts (60 pcs) - 1/4 in. D, 3 in. L, coarse, zinc-plated, grade 2 - [bolts](https://www.acehardware.com/departments/hardware/nuts-and-bolts/hex-bolts/57007) and [nuts](https://www.acehardware.com/departments/hardware/nuts-and-bolts/nuts/57248)
- Strap - [velcro](https://www.amazon.ca/VELCRO-Brand-Self-Gripping-Themselves-VEL-30834-AMS/dp/B09ZVJ8DSN/ref=sr_1_3_sspa?crid=33E3JRG8NR7X0&dib=eyJ2IjoiMSJ9.0YKgAcfGs7TG1CYkG4WJaWlhklOT5WrMBuz3DLOWvTlRz23uakKhuJ3iR_68oIuY33RdJQsmf8D54heMaVrt7CNHFaspy9_Upg-KGgle6f1rKHKgTeZ_VQDBOu929blKMabXzRKnavplupO8kwDcsBzp1xoIeEeraNkgo5Kl7v9PpnObZWCNrzTQGrKQzdcdI44Z-KtXwLe6Jv1YimvZ2nVuw6-kgjA2uL3YisidzgAdEOjNeOj-cBbHnjzN--w9WCJCqj7b2bkVCfvPBI0uO2VqtWaB_XoKb-Y6IP1Lah4.i55cFVtvz7CXRC5ojrNznE3lrM0QzYK1xllaD3Ot8rc&dib_tag=se&keywords=velcro&qid=1724254870&sprefix=velcr%2Caps%2C123&sr=8-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1)
- Acoustic Membrane (30 pcs) - for GAW334, we would need to contact distributors and/or manufacturers; those suggested by device support has a minimum purchase of 1040 pcs; [those](https://sinri.en.alibaba.com/product/50042020774-817207262/Sinri_IP67_protective_waterproof_eptfe_acoustic_vent_membrane_for_speaker.html?spm=a2700.icbuShop.41413.20.48264bbdxXWH09) suggested by model maker may have shipping issues; [some](https://micbooster.com/microphone-holders/124-acoustic-microphone-vent.html) I found online may also have shipping issues, with a different water resistance rating (IPX2 and IPX4) but might still be appropriate for our use

I tried to get the cheaper ones that would be good for general use since we don't need especially strong materials for our purposes.
@lizzieinvancouver, if you think there are better or cheaper sources, I'll try to find some more. I also have some more reservations on using either SLA or FDM for printing in terms of stability and water resistance, some quick search results [here](https://www.protolabs.com/resources/blog/prototyping-technologies-for-3d-printing-sla-vs-fdm/) and [here](https://hlhrapid.com/blog/sla-rapid-prototyping-advantages-and-disadvantages/). Also, if anyone has ideas for water resistance testing, feel free to chime in, right now @afong3 and I just thought of putting a piece of paper inside and spraying water around the case.

**Comment by lizzieinvancouver** [comment]
@kengi-neer Thanks. I ordered the velcro and O rings and asked about ordering through Alibaba... could you check the hex bolts and nuts through Ace Hardware .ca ?

**Comment by lizzieinvancouver** [comment]
@kengi-neer Amazon order of velcro and o-rings should arrive Wednesday.

**Comment by kengi-neer** [comment]
@lizzieinvancouver I didn't find any hex bolts or nuts in nearby Ace Hardware stores in BC. I found some in Canadian Tire though. [bolts](https://www.canadiantire.ca/en/pdp/hillman-hex-bolts-hexagonal-heads-machine-threads-zinc-plated-assorted-sizes-1617929p.1617934.html?rq=hex+bolts&colorCode=BOLT_DIAMETER_CD_1_4) and [nuts](https://www.canadiantire.ca/en/pdp/hillman-finish-hex-nut-for-general-applications-zinc-finish-1-4-20-in-1610467p.html?rq=hex+nuts). There's enough material (60 each) in the one in Marine Drive. I'll try to stop by and check if they fit tomorrow before buying or asking you to order them.

**Comment by lizzieinvancouver** [comment]
@kengi-neer Thanks. I also placed an order with Alibaba, but it will be several weeks or more before we receive it so it would be great if you can make notes to pass this task on.

**Comment by lizzieinvancouver** [comment]
@kengi-neer Ordered! I should have been able to get them delivered tomorrow but the site kept glitching -- they require you to add a reusable shopping bag for next day delivery but then they are out of stock of the bags (a rghh!). Anyway, order placed and arrives soon-ish.

<img width="979" alt="Screenshot 2024-08-27 at 3 31 02 PM" src="https://github.com/user-attachments/assets/09570110-2dbb-495f-85ad-1090c96b6cca">

**Comment by kengi-neer** [comment]
@afong3 and I discussed that the original design might be better than the remix version as the lid and body fit better, so less chance of water coming in. I tried fitting the hexbolts and nuts to all current cases, and the design might need to be modified a bit so they fit. Maybe we could also add the rain hood as with the remix and the green AudioMoth case.

In deciding whether to use FDM or SLA, I don't think we need strength that much. Our grey resin for SLA also needs to be used soon. Checking for stability under light might also take long. I think we can use SLA for now and just monitor it for the first use. We can also just hang a sample one over at the Totem Field and see what happens (if it will fall off due to breakage in the supports).

Also, @lizzieinvancouver, only 38 hexbolts was delivered according to the packing slip below (I also counted them).

![image_67160833](https://github.com/user-attachments/assets/de446c84-3e07-40a8-8cb6-42e643cb85aa)

**Comment by lizzieinvancouver** [comment]
> Also, @lizzieinvancouver, only 38 hexbolts was delivered according to the packing slip below (I also counted them).

I know! I am sorry about this. Canadian Tire annoyingly updated the order and shipped it without giving me any chance to cancel. When we need more we can order them or perhaps just pick some up. Do we need them now? 

I think the rest of the plan sounds good (I am not sure what you mean by the "rain hood" but trust you on this). I especially like the plan to get some out in the field and see how they do.

**Comment by kengi-neer** [comment]
@lizzieinvancouver No rush on these yet, I was just worried that they might have charged us more than what was received. I will try to set up the current cases near the greenhouse tomorrow.

**Comment by kengi-neer** [comment]
I set the cases near the greenhouse from Sept. 17 to Oct. 1 (as in the figure below).

![image_67515649](https://github.com/user-attachments/assets/349f0b95-c82b-4fc4-af3f-b360ad5012fd)
![image_67225857](https://github.com/user-attachments/assets/0197877b-522e-4c64-87d6-eb8f630594bd)

Both cases had some webs inside, but the FDM case had three insects and one spider inside. Water didn't seem to go inside the SLA case since the ink didn't smudge. The ink smudge in the FDM case might have been due to the insects and spider inside.

![image_67185409](https://github.com/user-attachments/assets/c20514b9-0d6d-43db-b01b-ecc0ec353010)
![image_67169281](https://github.com/user-attachments/assets/dcbd4760-e224-403b-9677-6771bf84d4f5)

@lizzieinvancouver Could you give me the log-in details for the lab tumblr?

**Comment by lizzieinvancouver** [comment]
Nice work!

> Could you give me the log-in details for the lab tumblr?

@kengi-neer Please ask @wangxm-forest or @christophe-rd -- they should have it.

**Comment by christophe-rd** [comment]
> Nice work!
> 
> 
> 
> > Could you give me the log-in details for the lab tumblr?
> 
> 
> 
> @kengi-neer Please ask @wangxm-forest or @christophe-rd -- they should have it.

Done!

**Comment by kengi-neer** [comment]
Designs for the case were from people who shared their files in thingiverse, see links in first comment.

These were produced by available 3D printers (and materials) in the lab, namely FDM (using PLA and ASA) and SLA (using Grey V4). Some notes below:

- Increasing wall loops and infill density for FDM prints allow for a better fit for the screws
- Lower infill density is recommended for ASA, 15% for the body seems to work and 25% for the lid so the hexbolt fits
- Need to find a way to make sure the print doesn't dislodge or have spaghetti failure when using ASA
- Use gloves when fitting tight bolts
- Sanding may be needed for SLA prints due to bumps left by supports, to avoid damage to the AudioMoths inside

Increasing the sizes of the holes may be recommended for a better fit for the screw, though this may vary by printing type and settings, as well as material (I think SLA prints allow for a smaller hole since the resin is more easily "bruised" to induce fit). However, this may be difficult to do using the available files since they have already been processed.

Water resistance was only tested using a piece of paper inside. Some of the ink seems to have spread, but this might be due to the humidity; a desiccant might help.

**Comment by kengi-neer** [comment]
Also, @lizzieinvancouver, you could use the images above or take a better picture of the cases in the lab to show Jonathan's former student, Ross, some of our assembled cases without the AudioMoth.

**Comment by lizzieinvancouver** [comment]
@kengi-neer My belated thanks! I sent an email to Ross last year.
