### ISSUE TITLE
Lab equipment purchasing: genetics stuff

### ISSUE THREAD

**Issue by wangxm-forest** [temporalecologylab/labgit#26]
@lizzieinvancouver We want to buy equipment for soil DNA extraction. I asked around and these are what I found so far:

**Vortex** (plus vortex adapter - Qiagen cat. no. 13000-V1-24)
[ThermoFisher](https://www.thermofisher.com/order/catalog/product/88882009?SID=srch-srp-88882009)
Pros:

- Handle more samples at once
- Digital

Cons:

- Pricey

[WestLab](https://www.westlab.com/vortex-mixer-isg)
Pros:

- Cheap

Cons:

- Can only handle one sample and you have to do it manually

**Centrifuge 16,000x g standard benchtop, as around…**
[ThermoFisher](https://www.thermofisher.com/ca/en/home/life-science/lab-equipment/lab-centrifuges/benchtop-centrifuges/models/selection.html) Here's a list of all centrifuge ThermoFisher is selling, you can roll down to see the ones with  Max. RCF of 17000 x g, and most of them can take 24 samples.

[Fresco™ 17 Microcentrifuge Refregirated](https://www.thermofisher.com/order/catalog/product/75002421)
This model have the temperature range of: -9℃-40℃, since we are dealing with DNA, probably the ability to operate at low temperature is an important thing?

**Microcentrifuge for travel:**
[WeberScientific](https://www.weberscientific.com/mc-12-high-speed-centrifuge-benchmark-scientific)
Pros:
- speed we need;
- relatively small and light
- minimizes sample temperature increases during longer runs at high speeds

Cons:
- can only take 12 samples
- only 1 year warranty

Pipettes (P20, P100, P1000)

Pipettes prices can vary a lot. [ThermoFisher](https://www.thermofisher.com/order/catalog/product/4641010N?SID=srch-srp-4641010N) ones are around 800 CAD each and [WestLab](https://www.westlab.com/westlab-single-channel-pipette-5-options) ones are about 300 CAD each.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
Hi Lizzie, how many pipette tips should we order from this purchase?

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Since pipette tips are supplies I think we should not order them yet. 

I never heard back from David Lipson -- I'll ping him once more, but then we should pick out a centrifuge on our own.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest David did not have specific recommendation for a centrifuge. Here's what I got:

> Sorry, Lizzie. I was going to visit my friend's lab where she has some little centrifuges and see what type they were, but it keeps slipping my mind when I'm on campus. I love the story of the kids that made a centrifuge from a saladspinner for red blood cell collection in remote areas. 
> 
> For pipettes, I like Gilson, if they still make them. I have some Finnpipettes, too. I think they are generally fine.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
I finally heard back from Thermo Fisher, and they have a package available that includes both a microcentrifuge and the pipettes we need. Here's an image of the package:
![image](https://github.com/user-attachments/assets/86cf53b6-7605-48d1-92ae-07a149d04876)

The centrifuge is a bit larger than the one from WeberScience (22.5 x 24.3 x 35.2 cm vs. 27 x 22 x 15 cm), but it has a higher capacity, holding up to 24 samples. I think this one should work well for our needs.

I think we can also consider this as our benchtop centrifuge, or would you prefer we look into a larger model, such as one with dual rows to accommodate tubes of different volumes?

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Thanks! How much is it and does it meet the RPM we need (for the DNAeasy kit)? How much would a 48 sample benchtop model cost?

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
1. Yes, this microcentrifuge meet the RPM we need, it holds 24 2mL tubes and can go to 17000 xg.
2. Here's the quote I got from them, and I believe this is before the CFI discount. I will ask them for a CFI discount in my following email, but could you please take a look at these items.
<img width="542" alt="613c6b0d43e57471cf9c1edc4f36a94" src="https://github.com/user-attachments/assets/8dddfccd-9674-4bbc-b498-e0e6c88aa458">

The first item is a tabletop centrifuge.
The second item is a Microliter rotor which is compatible with the first centrifuge and make it able to handle 48 2mL tubes at once. 
The third item is the package they were promoting, with the pipettes, microcentrifuge and pipette tips.

Please let me know what do you think.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Thanks! Can you give me some of the specs for the benchtop centrifuge? I have not been able to find it online. Can you also let me know what type of pipettes the kit includes? I worry they may use the kit as a way to sell pipettes that are not great, but am not sure. 

Does anyone sell the Gilson that David mentioned pipettes in Canada?

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
The benchtop centrifuge is [this](https://www.thermofisher.com/order/catalog/product/75007200) one.
It allows us to handle 48 microtubes when equipped with the Microliter rotor, while the microcentrifuge in the package will not be able to handle 48 samples at the same time.

Pipettes the kit includes are Finnpipette F2, I looked online and many people like these pipette saying that they are smooth and sturdy.
If you prefer Gilson, we can directly order from their [website](https://ca.gilson.com/CASV/shop-products/pipettes.html?pipette_range=12580)
The price will also be a little bit cheaper if we go with Gilson.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver Hi Lizzie, have you decided which centrifuge and pipettes should we get?

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Sorry for the delay. I thought about it and I think we should SKIP the bench top one if the smaller one will work for our DNA purposes. (We can also visit another lab at UBC and borrow their centrifuge if we really need it.) So can you please order the smaller one and some Gilson pipettes? I leave it to you to decide we should get the kit and have extra pipettes or order separately.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
I ordered the PIPETMAN Starter Kits from Gilson, which include the 2-20 µL, 20-200 µL, and 100-1000 µL pipettes. I know you requested the 20 µL, 100 µL, and 1000 µL, but unfortunately, they don’t sell them as a kit. I called their customer service to ask if we could exchange the 200 µL pipette for a 100 µL one, but had a very poor experience...They just hung up on me. I’ve also sent them an email. I'll see how it goes.

If they can’t change the 200 µL pipette for us, I believe the three pipettes in that kit should still be suitable for the work according to the manual you sent me.

**Comment by wangxm-forest** [comment]
I reached out to ThermoFisher to ask if their vortex would be compatible with the Qiagen Vortex Adapter, but they were not sure either. Given this, I recommend that, instead of purchasing the ThermoFisher vortex, we buy the [Vortex-Genie 2 Vortex] (https://www.grainger.ca/en/product/p/WWG13R284?cm_mmc=PPC:+Google+PLA&gucid=N:N:PS:Paid:GGL:CSM-8500:NOYSQ4:20501231:APZ_1&gad_source=4&gclid=CjwKCAiAudG5BhAREiwAWMlSjOdP7TaKEPCT8UvnZVHewyOkKNXVOCq54GatsUyv4nBxou1bhSeS8BoCVEAQAvD_BwE&gclsrc=aw.ds) as recommended on the Qiagen Vortex Adapter website to make sure they will be compatible with each other.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest That sounds good!

**Comment by wangxm-forest** [comment]
@lizzieinvancouver Hi Lizzie, I placed an order for the vortex adapter from [Qiagen](https://www.qiagen.com/ca/products/instruments-and-automation/accessories/vortex-adapter), which allows us to shake 24 tubes at the same time on a vortex.

However, I called Qiagen, and they told me that the item is currently not available until the end of this month and they couldn't invoice us until the item has been shipped.
Given that the deadline for submitting all invoices is at the end of this month, I'm concerned that we may not be able to process this purchase in time.
Would you still like to proceed with the order, even if we cannot put the cost to the equipment money? The total for this item is CA$383.16.
Sorry for being last minute.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver Just received the invoice from Qiagen today and I've already submitted it!

I only need to get a PO for Thermo Fisher and we will be all set! I already double checked with Thermo Fisher and they will be able to invoice us immediately after we place the order.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Great! I am sorry the clauses are such a pain.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Feel free to close this when you think it is done! And thank you again!

**Comment by wangxm-forest** [comment]
@lizzieinvancouver I just received the Qiagen package today. I will close this issue when the order from ThermoFisher is confirmed.

**Comment by wangxm-forest** [comment]
The very last order confirmed! It is back ordered and will be shipped on Dec. 30.
