### ISSUE TITLE
new whiteboard for lab?

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#27]
@wangxm-forest @christophe-rd @afong3 We may have funds for a new whiteboard in the lab. I am checking on costs ... could someone review [the sizes here](https://egan.com/wp-content/uploads/GlassWrite-MAG_Spec-Sheet.pdf) and let me know which would fit best. Thank you!

**Comment by christophe-rd** [comment]
@lizzieinvancouver is it a wall whiteboard to replace the one we already have? Would you like to purchase a third one on wheels?

**Comment by lizzieinvancouver** [comment]
@christophe-rd I was thinking to replace the wall one with a nicer glass one.

**Comment by lizzieinvancouver** [comment]
@afong3 @wangxm-forest @christophe-rd Could someone send me the dimensions?

**Comment by christophe-rd** [comment]
@lizzieinvancouver the one that is currently on the wall is 1.2x1.2 meters.
However, if we want to increase in size we can go up 1.75 meters in width and 1.4 in height.

**Comment by lizzieinvancouver** [comment]
@christophe-rd Thank you!

**Comment by lizzieinvancouver** [comment]
@christophe-rd @wangxm-forest @lizzieinvancouver I am getting a whiteboard for the lab, but it will be glass. I am planning to get clear, but if you want another [color](https://materiallibrary.egan.com/product-category/glass/) please tell me within 24 hours. Thanks!

**Comment by christophe-rd** [comment]
Sorry! I missed your deadline. Clean is fine with me!
