### ISSUE TITLE
Check daily logs

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#3]
@dbuona  @cchambe12 I will email you each some daily logs, can you check them (no rush!) for whether they have any info we should not put in a public repo (passwords, really awkward honesty etc.) ... and @dbuona if there is any pertinent cutting experiment info for @DeirdreLoughnan can you make some notes/flag the important info? Thank you! (And zero rush.)

**Comment by cchambe12** [comment]
All clean!  Nothing terribly enlightening.

**Comment by dbuona** [comment]
Tim's also clean, only thing that might be useful is how to find specific species at field site but now that they are GPS'ed, probably unnecessary.

**Comment by lizzieinvancouver** [comment]
Almost four years later and I think time to close this!
