### ISSUE TITLE
equipment purchasing: electric saw

### ISSUE THREAD

**Issue by christophe-rd** [temporalecologylab/labgit#30]
@lizzieinvancouver I am planning ahead for my biomass and tree cookie collection next fall and thought that we could buy an electric chainsaw. Something small and precise would be great. E.g.: https://www.homedepot.ca/product/dewalt-20v-max-8-inch-pruning-chainsaw-tool-only-/1001738417
 
No, I don't think it's absolutely necessary, but it think it will save me a lot of time when I will be in a rush to harvest tree cookies next year.

**Comment by christophe-rd** [comment]
@FrederikBaumgarten @wangxm-forest @DeirdreLoughnan I never collected trees for cookies and biomass. Do you have suggestions on any equipment that could be useful that the lab doesn't have?

**Comment by christophe-rd** [comment]
@lizzieinvancouver I added this into the expense folder as a desired item. I will remove it if you don't think we should buy this

**Comment by lizzieinvancouver** [comment]
@christophe-rd Can you link to the file and tell me which tab you entered this in? I am struggling to find anything newer than June in the two tabs I thought it would be in ...

**Comment by lizzieinvancouver** [comment]
@christophe-rd Wait, I found it ... I see @afong3 added stuff from earlier. @afong3 Can you confirm ASAP that what you added is all reimbursed? I am trying to budget and need to know what is reimbursed....

**Comment by lizzieinvancouver** [comment]
@christophe-rd As long as you will use the saw and @wangxm-forest has a good place to keep it, you can buy it.

**Comment by christophe-rd** [comment]
Ok thanks! I'll buy it today.

**Comment by afong3** [comment]
@lizzieinvancouver I added all of the receipts that I emailed to Christine to the spreadsheet yesterday, so all should be accounted for from my end.

**Comment by lizzieinvancouver** [comment]
> Oh! It's not compatible with our batteries. Sorry about that. What about getting 2 good quality pruning saws like these: [Samurai](https://www.amazon.ca/Samurai-Ichiban-Curved-Pruning-Scabbard/dp/B001BAFD6E)
> 
> [Silky](https://www.amazon.ca/Silky-Professional-Folding-Landscaping-356-36/dp/B0014CA3JQ/ref=sr_1_4?crid=19RIPKCR7OXI3&dib=eyJ2IjoiMSJ9.8-SwJEuLS24UaAkwg2s7z72Z3AG9Qs2cSjAEQNRu45verjLrru56KHtTZMCeYCdqkctSa1KcD16zWz0gP8iNF6kGxmUxBVVzCrVtnnuAs1JWXZ_g5D-14oCXhFe6HYvGnIqGH4CUZzppA4ezyF9QS42qU3YEaWhETjucCAtU2nTJxUVe9pf-ipyFy1fbo2lWxai_gF8CKvsfbif3LDY6tAooZTTA3Y8F59Lv26nh_7BV4SLKxR8l0j-uYELBjPA_4NrEFOTvE_MQWfRiX2Bka2U1thfvHw8HMwLegfFeIC4.5NPhdtSPK3Qq-qB0806RVm17FX4hRgVeSJNBMAAdxcI&dib_tag=se&keywords=Silky&qid=1731088442&sprefix=silky%2Caps%2C151&sr=8-4&ufe=INHOUSE_INSTALLMENTS%3ACA_IHI_3M_AUTOMATED)

@christophe-rd Sure.

**Comment by lizzieinvancouver** [comment]
@christophe-rd Can we close this if you bought one?

**Comment by christophe-rd** [comment]
Yes!
