### ISSUE TITLE
equipment purchasing: fast ssd

### ISSUE THREAD

**Issue by christophe-rd** [temporalecologylab/labgit#31]
It took 2 hours yesterday to transfer 6 cookies to the micro sd card. I slows down the process. I thought buying a really fast ssd like this would help:

https://a.co/d/2IdsWkH
Or
https://a.co/d/7bRoodl

Or a usb c key like this:
https://a.co/d/91RUGGL

Or both.

**Comment by lizzieinvancouver** [comment]
Good idea, can you get the USB-C key and also: [this](https://www.amazon.ca/Samsung-Portable-External-MU-PC2T0H-AM/dp/B0874Y5XFG) and [this](https://www.amazon.ca/SanDisk-2TB-Portable-SSD-SDSSDE30-2T00-G26/dp/B0C5JNWF58). Thanks!

**Comment by christophe-rd** [comment]
@lizzieinvancouver ordered! I'm closing this issue.
