### ISSUE TITLE
equipment: microscrope

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#32]
From @wangxm-forest:

> I met with Thomas today to check out the Leica microscopes. He brought two models: one that I was specifically looking for and another that he recommended.
> 
> I asked him to send us quotes for both microscopes. The model I was interested in is approximately 3000 CAD, while the recommended one is around 7000 CAD. I asked him and he said we could ask for a discount, but not much. The more expensive model has an in-built camera for taking photos and videos, and it can also perform measurements when connected to a monitor. Also, it is more compatible and can be customized based on our needs.
> 
> While the more advanced model is impressive, I think the basic one would meet our requirements for our cores. Unless you think we might have any additional needs in the future, I think we don't have to spend that much money on the microscope.
> 
> I haven't heard back from Zeiss yet, but I will send them a follow-up email. I’ve confirmed with Christine that for orders under 3000 CAD, we don’t need multiple quotes.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver Hi Lizzie. Thomas asked if we’d be interested in buying the demo unit. The demo unit he’s referring to is the one he brought to our lab, which was brand new the last time he showed it to us. I’ve confirmed with him that the demo unit will come with the same warranty.

The reason he’s offering this option is that it might take a bit longer to process a quote with the CFI discount for a brand new unit from Leica.

Would you consider buying the demo unit? I’ve also received the updated quote from them, and they’ve offered us a 20% CFI discount, plus an additional 2.5% demo unit discount. The total will be 2394.76 CAD

**Comment by lizzieinvancouver** [comment]
@wangxm-forest I would be fine with the demo unit if they offered a larger discount but 2.5% is nothing so I am not okay with that (it may be new, but it has bounced around in travel a lot). If they want to increase to 10% then we could buy the demo, but otherwise we need to encourage them to get us a quote on a new unit (or considering buying another brand).

**Comment by wangxm-forest** [comment]
I ordered the new unit with the CFI discount. The microscope will be shipped to us in December. And I've already submitted the invoices.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Hurray!!! Thank you!
