### ISSUE TITLE
equipment: plastic boxes

### ISSUE THREAD

**Issue by christophe-rd** [temporalecologylab/labgit#34]
An idea I had. To help organize equipment in the lab, we could buy a bunch of plastic (I prefer transparent) boxes that stack well. I found the best quality prices are the IKEAs. Bellow are a suggestion of how many of each we could get. This a total of 270$
![Screenshot 2024-11-07 at 11 01 39 AM](https://github.com/user-attachments/assets/ed539ec7-4c1c-43cc-8e61-4a617a803c26)
![Screenshot 2024-11-07 at 11 01 48 AM](https://github.com/user-attachments/assets/b28ea6be-d1ea-45eb-a2ed-e05c2148c740)

**Comment by wangxm-forest** [comment]
Great idea! I also suggest we get some boxes to help keep things more organized. However, before making any purchases, I think it would be best to take some measurements in the lab first to determine what sizes and how many boxes we can fit.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest @christophe-rd This is a great idea! If you need to get any nicer ones for some reason, we can also spend more.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver I've purchased the boxes. We bought 10 small boxes, 10 medium boxes and 4 big boxes from IKEA. Hopefully these will help make lab space more organized.
