### ISSUE TITLE
temporalecology: research page

### ISSUE THREAD

**Issue by lizzieinvancouver** [temporalecologylab/labgit#9]
@toluam Do you think we could add photos to some of the projects on the research page? I imagine a big one (sort of like if you scroll down [here](https://levine.princeton.edu/) to maintenance of diversity) and the text beside it (so two columns) and then beneath in slightly smaller text perhaps (or at least with less white space between lines) we put in the pubs.

Also, please for lists of pubs:
- [x] keep the text color the same too 
- [x] merge "Read more about this work in:" into each pubs element or box (so the text about the project is fully separate)

**Comment by toluam** [comment]
@lizzieinvancouver I've updated the research page - let me know if you like how the page looks with the new layout or if you'd like me to keep tweaking it

**Comment by lizzieinvancouver** [comment]
@toluam I love (love!) this new look!

Small tweaks -- could change a few photos?

- Could you replace the photo of me (though I love that one) in first section with some new common garden photos. I uploaded some just now to 2022 Boston fieldwork 

- And could you replace the first two photos that go with 'How does intra- and inter-annual time assemble communities?' with some of these photos:

2021 July Smithers -- perhaps incl. 2021Jul15_Smithers04 ?
2020 June Rannier -- 2020June18_Rainier246 or 2020June18_Rainier250
I like the one of cat (pink jacket looking at twigs) though as it is placed right next to her papers from that work! So please keep the last one where it is. 

Thank you!

**Comment by toluam** [comment]
@lizzieinvancouver I'm unable to locate the Rainier246 or Rainier250 pictures on the google drive but I used another picture from that folder. Let me know if you like how it looks.

**Comment by lizzieinvancouver** [comment]
@toluam Thanks! I'd prefer not to use the second image under: How does intra- and inter-annual time assemble communities? as it's not us. I just added those image to the drive and will email you one -- can you swap it out? Thank you!

**Comment by lizzieinvancouver** [comment]
@toluam Looks great -- thank you!
